project_id = "duclndrnymarwhmbtjgl"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.voice-assistant]
verify_jwt = false

[functions.aadhaar-auth]
verify_jwt = false
